apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        prometheus.io/path: actuator/prometheus
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: registry.kube-system.svc.cluster.local:80/bomc/consumer:OVERRIDEN_IN_OVERLAYS
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 360Mi
          limits:
            cpu: 400m
            memory: 360Mi
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 25
          periodSeconds: 30
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File