apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: default
  labels:
    app: consumer
spec:
  selector:
    app: consumer
  ports:
  - protocol: TCP
    name: 8081-tcp
    port: 8081
    targetPort: 8081