apiVersion: v1
# Set a quota for the total number of Pods that can run in a namespace
kind: ResourceQuota
metadata:
  name: consumer-object-quota
  namespace: default
  labels:
    app: consumer
spec:
  hard:
    pods: "2"
    requests.cpu: "20m"
    requests.memory: 720Mi
    limits.cpu: "100m"
    limits.memory: 720Mi
    services.nodeports: "0"