apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./000-namespace.yaml
- ./010-dc.yaml
- ./020-svc.yaml
#- ./030-resource-quotas.yaml

commonLabels:
  app.kubernetes.io/name: bomc-consumer-app
