apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bomc-consumer-prod
bases:
- ./../../base/
commonLabels:
  environment: prod

images:
- name: localhost:5000/bomc/consumer
  newName: localhost:5000/bomc/consumer
  newTag: 04911b76f9541d0088f65fab39813fe0ee130998

patchesJson6902:
- path: namespace-patch.json
  target:
    kind: Namespace
    name: default
    version: v1
---