apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bomc-consumer-prod
bases:
- ./../../base/
commonLabels:
  environment: prod

images:
- name: 192.168.99.144:5000/bomc/consumer
  newName: 192.168.99.144:5000/bomc/consumer
  newTag: latest

patchesJson6902:
- path: namespace-patch.json
  target:
    kind: Namespace
    name: default
    version: v1
---