apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bomc-consumer-prod
bases:
- ./../../base/
commonLabels:
  environment: prod

images:
- name: localhost:5000/bomc/consumer
  newName: localhost:5000/bomc/consumer
<<<<<<< HEAD
  newTag: v0.0.6
=======
  newTag: v0.0.1
>>>>>>> ae35d4e (set version to v0.0.1)

patchesJson6902:
- path: namespace-patch.json
  target:
    kind: Namespace
    name: default
    version: v1
---