apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bomc-consumer-prod
bases:
- ./../../base/
commonLabels:
  environment: prod
images:
- name: localhost:5000/bomc/buildah-consumer
  newName: localhost:5000/bomc/buildah-consumer
  newTag: cc30d6f369d0172e9460673b6e20c7362274c8c5
patchesJson6902:
- path: namespace-patch.json
  target:
    kind: Namespace
    name: default
    version: v1
---